services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
      args:
        - port=3000
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn prisma:gen:gateway && yarn start:dev:gateway'
    depends_on:
      - db
      - minio
    networks:
      - api-network
    ports:
      - '3000:3000'
    environment:
      - GATEWAY_DATABASE_URL=postgres://user:admin@db:5432/nodejs_db
      - S3_CONNECTION_STRING=http://minio:9000
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    restart: always
    networks:
      - api-network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nodejs_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-16T23-46-41Z
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - api-network
    volumes:
      - minio-data:/data

volumes:
  local_pgdata:
  minio-data:

networks:
  api-network:
    driver: bridge
