services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
      args:
        - port=3000
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn prisma:gen:gateway && yarn start:dev:gateway'
    depends_on:
      - db
    networks:
      - api-network
    ports:
      - '3000:3000'
    environment:
      - GATEWAY_DATABASE_URL=postgres://user:admin@db:5432/nodejs_db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    restart: always
    networks:
      - api-network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nodejs_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:

networks:
  api-network:
    driver: bridge
