apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: PHOTO_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: PHOTO_SERVICE_PORT
             - name: PHOTO_DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: PHOTO_DATABASE_URL
             - name: S3_ACCESS_KEY
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: S3_ACCESS_KEY
             - name: S3_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: S3_SECRET_KEY
             - name: S3_CONNECTION_STRING
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: S3_CONNECTION_STRING
             - name: S3_BUCKET_NAME
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: S3_BUCKET_NAME
             - name: S3_PUBLIC_URL
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: S3_PUBLIC_URL
             - name: S3_REGION
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: S3_REGION
             - name: PHOTO_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: somegram-files-production-config-secret
                   key: PHOTO_SERVICE_HOST
