apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: MESSENGER_SERVICE_POR
               valueFrom:
                 secretKeyRef:
                   name: somegram-messenger-production-config-secret
                   key: MESSENGER_SERVICE_POR
             - name: MESSENGER_DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: somegram-messenger-production-config-secret
                   key: MESSENGER_DATABASE_URL
             - name: RMQ_CONNECTION_STRING
               valueFrom:
                 secretKeyRef:
                   name: somegram-messenger-production-config-secret
                   key: RMQ_CONNECTION_STRING
             - name: MESSENGER_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: somegram-messenger-production-config-secret
                   key: MESSENGER_SERVICE_HOST
