export const PAYPAL_CLIENT = 'PAYPAL_CLIENT';
export const PAYPAL_ORDERS_CONTROLLER = 'PAYPAL_ORDERS_CONTROLLER';
export const PAYPAL_PAYMENTS_CONTROLLER = 'PAYPAL_PAYMENTS_CONTROLLER';
export const PAYMENTS_SERVICE_RMQ = 'PAYMENTS_SERVICE_RMQ';
export const NOTIFICATION_SERVICE_RMQ = 'NOTIFICATION_SERVICE_RMQ';
export const NOTIFICATION_DELAY_SERVICE_RMQ = 'NOTIFICATION_DELAY_SERVICE_RMQ';
