apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: STRIPE_SIGNATURE_SECRET
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: STRIPE_SIGNATURE_SECRET
             - name: PAYMENTS_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: PAYMENTS_SERVICE_HOST
             - name: PAYMENTS_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: PAYMENTS_SERVICE_PORT
             - name: PAYMENTS_DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: PAYMENTS_DATABASE_URL
             - name: FRONTEND_SUCCESS_PAYMENT_URL
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: FRONTEND_SUCCESS_PAYMENT_URL
             - name: FRONTEND_CANCEL_PAYMENT_URL
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: FRONTEND_CANCEL_PAYMENT_URL
             - name: RMQ_CONNECTION_STRING
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: RMQ_CONNECTION_STRING
             - name: STRIPE_API_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: some-payments-service-production-config-secret
                   key: STRIPE_API_SECRET_KEY
